log_setting:
   loglevel : 1  #1=DEBUG, 2=ERROR         DEBUG > ERROR
   log_to_console: False
   # logpath : '/home/bddml/DynamicCI_Redesign/DynamicIndexinglog/'
   # logpath : 'D:\\Downloads\\PredictionModule_upsert\\PredictionModule_upsert\\DynamicIndexinglog\\'
      